spring:
  datasource:
    first:
      url: jdbc:mysql://${boot.first.host}:${boot.first.port}/${boot.first.database}?${boot.first.params}
      username: ${boot.first.username}
      password: ${boot.first.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      url: jdbc:mysql://${boot.second.host}:${boot.second.port}/${boot.second.database}?${boot.second.params}
      username: ${boot.second.username}
      password: ${boot.second.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: maxwell
    username: admin
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  global-config:
    banner: false
boot:
  host: localhost
  port: 3306
  params: useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  database: user
  username: root
  password: Zyc19980518@
  first:
    username: ${boot.username}
    password: ${boot.password}
    params: ${boot.params}
    host: ${boot.host}
    port: ${boot.port}
    database: user
  second:
    username: ${boot.username}
    password: ${boot.password}
    params: ${boot.params}
    host: ${boot.host}
    port: ${boot.port}
    database: exam

