package com.example.boot.mapper;

import com.example.boot.mapper.dynamic.UserDynamicMapper;
import com.example.boot.model.User;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.SelectKey;
import org.mybatis.dynamic.sql.insert.render.InsertStatementProvider;
import org.mybatis.dynamic.sql.util.SqlProviderAdapter;
import pro.chenggang.project.reactive.mybatis.support.r2dbc.dynamic.ReactiveMyBatis3Utils;
import reactor.core.publisher.Mono;

/**
 * auto generated mapper
 * 
 * @author autoGenerated
 */
@Mapper
public interface UserMapper extends UserDynamicMapper {


}